SBC = {
    "1": "Wait a minute.",
    "2": "Very Important.",
    "3": "What time is it?",
    "4": "Where shall I go ahead?",
    "5": "Have you business for me?",
    "6": "I am ready.",
    "7": "Are you ready?",
    "8": "Close your key, stop breaking.",
    "9": "Priority business. Wire Chief's call.",
    "10": "Keep this circuit closed.",
    "12": "Do you understand?",
    "13": "I understand.",
    "14": "What is the weather?",
    "15": "For you and others to copy.",
    "17": "Lightning here.",
    "18": "What's the trouble?",
    "19": "Form 19 train order.",
    "21": "Stop for meal.",
    "22": "Wire test.",
    "23": "All stations copy.",
    "24": "Repeat this back.",
    "25": "Busy on another wire.",
    "26": "Put on ground wire.",
    "27": "Priority, very important.",
    "28": "Do you get my writing?.",
    "29": "Private, deliver in sealed envelope.",
    "30": "No more - the end.",
    "31": "Form 31 train order.",
    "32": "I understand that I am to ....",
    "33": "Answer is paid.",
    "34": "Message for all officers.",
    "35": "You may use my signal to answer this.",
    "37": "Inform all interested.",
    "39": "Important, with priority on through wire.",
    "44": "Answer promptly by wire.",
    "55": "Important.",
    "73": "Best Regards.",
    "77": "I have a message for you.",
    "88": "Love and kisses.",
    "91": "Superintendent's signal.",
    "92": "Deliver Promptly.",
    "134": "Who is at the key?"
};